name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v2.1.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - run: dart --version
      - run: pub get
      - run: pub global activate grinder
      - name: Package and publish
        run: grind pkg-github-all
